import Head from 'next/head'
import Navbar from '@components/Navbar';
import 'animate.css';
import Code from '@components/Code';

export default function Animate() {

  return (
    <>
      <Head>
        <title>Animate CSS | Next Animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold mb-8">Animate CSS</h1>

          <div className="dark:text-gray-100 text-xl space-y-3">
            <p className="animate__animated animate__slow animate__bounce">Bounce</p>
            <p className="animate__animated animate__slow animate__flash">Flash</p>
            <p className="animate__animated animate__slow animate__shakeX">Shake X</p>
            <p className="animate__animated animate__slow animate__swing">Swing</p>
            <p className="animate__animated animate__slow animate__tada">Tada</p>
            <p className="animate__animated animate__slow animate__heartBeat">heartBeat</p>
            <p className="animate__animated animate__slow animate__fadeInDown">Fade in Down</p>
            <p className="animate__animated animate__slow animate__zoomIn">Zoom In</p>
            <p className="animate__animated animate__slow animate__slideInDown">Slide in Down</p>
            <p className="animate__animated animate__slow animate__rollIn">Roll In</p>
          </div>

          <Code code={`import 'animate.css';

export default function Animate() {
  return (
    <p class="animate__animated animate__slow animate__bounce">Bounce</p>
    <p class="animate__animated animate__slow animate__flash">Flash</p>
    <p class="animate__animated animate__slow animate__shakeX">Shake X</p>
    <p class="animate__animated animate__slow animate__swing">Swing</p>
    <p class="animate__animated animate__slow animate__tada">Tada</p>
    <p class="animate__animated animate__slow animate__heartBeat">heartBeat</p>
    <p class="animate__animated animate__slow animate__fadeInDown">Fade in Down</p>
    <p class="animate__animated animate__slow animate__zoomIn">Zoom In</p>
    <p class="animate__animated animate__slow animate__slideInDown">Slide in Down</p>
    <p class="animate__animated animate__slow animate__rollIn">Roll In</p>
  )
}`} />

        </div>
      </main >
    </>
  )
}
