import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css'; // You can also use <link> for styles
import Code from '@components/Code';
// ..
// AOS.init();

export default function Aos() {

  useEffect(() => {
    AOS.init();
  }, [])
  

  return (
    <>
      <Head>
        <title>AOS Animate on Scroll | Next Animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 overflow-hidden">
          <h1 className="dark:text-white text-2xl font-semibold mb-2">AOS Animate on Scroll</h1>
          <p className="text-sm dark:text-white mb-8">use overflow-hidden to fix on mobile</p>

          <div className="dark:text-gray-100 text-xl space-y-3">
            <p data-aos="fade-up">Fade Up</p>
            <p data-aos="fade-right">Fade Right</p>
            <p data-aos="flip-left">Flip Left</p>
            <p data-aos="flip-up">Flip Up</p>
            <p data-aos="zoom-in">Zoom In</p>
            <p data-aos="zoom-out">Zoom Out</p>
            <div data-aos="fade-up" data-aos-duration="3000">
                Fade Up Duration
            </div>
          </div>

          <Code code={`import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';

export default function Aos() {
  useEffect(() => {
    AOS.init();
  }, [])
  
  return (
    <p data-aos="fade-up">Fade Up</p>
    <p data-aos="fade-right">Fade Right</p>
    <p data-aos="flip-left">Flip Left</p>
    <p data-aos="flip-up">Flip Up</p>
    <p data-aos="zoom-in">Zoom In</p>
    <p data-aos="zoom-out">Zoom Out</p>
    <div data-aos="fade-up" data-aos-duration="3000">
        Fade Up Duration
    </div>
  )
}`} />

        </div>
      </main >
    </>
  )
}
