import Head from 'next/head'
import Navbar from '@components/Navbar';
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import Code from '@components/Code';

const squareVariants = {
  visible: { opacity: 1, scale: 1, transition: { duration: 0.7 } },
  hidden: { opacity: 0, scale: 0.9 }
};
function Square() {
  return (
    <>
      <motion.div
        whileInView="visible"
        initial="hidden"
        variants={squareVariants}
        className="bg-red-500 h-64 w-64"
      ></motion.div>
    </>
  );
}

export default function Scroll() {
  const shouldReduceMotion = useReducedMotion();
  const { scrollYProgress } = useScroll()
  const scale = useTransform(scrollYProgress, [0, 1], [5, 10]);

  return (
    <>
      <Head>
        <title>Framer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4">
          {/* <h1 className="dark:text-white text-2xl font-semibold">Framer</h1> */}

          <div className="grid sm:grid-cols-2 gap-16 my-28">
            <div className="flex items-center justify-center">
              <motion.div className="dark:text-white text-5xl font-bold"
                initial={{ y: shouldReduceMotion ? 0 : 50, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 0.5 }}
              >
                Title
              </motion.div>
            </div>
            <div className="flex justify-center">
              <motion.div className="dark:text-white text-5xl"
                initial={{ scale: shouldReduceMotion ? 1 : 1.5, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ duration: 0.75 }}
              >
                <div className="bg-red-500 h-64 w-64">
                </div>
              </motion.div>
            </div>
          </div>

          <motion.div className="flex justify-center my-16"
            style={{ scale }}
          >
            <motion.div className="bg-red-500 h-32 w-32"
              style={{
                scaleY: scrollYProgress
              }}
            />
          </motion.div>

          <div className="flex flex-col gap-16 space-y-16 my-16">
            <Square />
            <Square />
            <Square />
            <Square />
          </div>


          <Code code={`import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
          
const shouldReduceMotion = useReducedMotion();
const { scrollYProgress } = useScroll()
const scale = useTransform(scrollYProgress, [0, 1], [0.5, 2]);

<div className="flex items-center justify-center">
  <motion.div className="dark:text-white text-5xl font-bold"
    initial={{ y: shouldReduceMotion ? 0 : 50, opacity: 0 }}
    animate={{ y: 0, opacity: 1 }}
    transition={{ duration: 0.5 }}
  >
    Title
  </motion.div>
</div>
<div className="flex justify-center">
  <motion.div className="dark:text-white text-5xl"
    initial={{ scale: shouldReduceMotion ? 1 : 1.5, opacity: 0 }}
    animate={{ scale: 1, opacity: 1 }}
    transition={{ duration: 0.75 }}
  >
    <div className="bg-red-500 h-64 w-64">
    </div>
  </motion.div>
</div>
</div>

<motion.div className="flex justify-center mt-32"
style={{ scale }}
>
<motion.div className="bg-red-500 h-32 w-32"
  style={{
    scaleY: scrollYProgress
  }}
/>
</motion.div>`} />

        </div>
      </main >
    </>
  )
}