import Head from 'next/head'
import Navbar from '@components/Navbar';
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import Code from '@components/Code';

function Square() {
  return (
    <>
      <motion.div
        initial={{ opacity: 0, scale: 0.75, y: 50 }}
        whileInView={{ opacity: 1, scale: 1, y: 0, transition: { duration: 0.75, type: "spring", stiffness: 300, damping: 20 } }}
        className="bg-yellow-500 h-52 w-52 rounded"
      ></motion.div>
    </>
  );
}

export default function Scroll() {
  const shouldReduceMotion = useReducedMotion();
  const { scrollYProgress } = useScroll()
  const scale = useTransform(scrollYProgress, [0, 1], [1, 3]);

  const backwardsY = useTransform(scrollYProgress, [0, 1], ["0", "-700px"]);
  const forwardsY = useTransform(scrollYProgress, [0, 1], ["0", "200px"]);
  const backwardsX = useTransform(scrollYProgress, [0, 1], ["0", "-200px"]);
  const forwardsX = useTransform(scrollYProgress, [0, 1], ["0", "200px"]);

  return (
    <>
      <Head>
        <title>Framer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4">
          {/* <h1 className="dark:text-white text-2xl font-semibold">Framer</h1> */}

          <div className="grid sm:grid-cols-2 gap-16 my-28">
            <div className="flex items-center justify-center">
              <motion.div className="dark:text-white text-5xl font-bold"
                initial={{ y: shouldReduceMotion ? 0 : 50, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ duration: 0.5 }}
              >
                Title
              </motion.div>
            </div>
            <div className="flex justify-center">
              <motion.div className="dark:text-white text-5xl"
                initial={{ scale: shouldReduceMotion ? 1 : 1.5, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ duration: 0.75 }}
              >
                <div className="bg-red-500 h-64 w-64">
                </div>
              </motion.div>
            </div>
          </div>

          <Code code={`import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
 
const shouldReduceMotion = useReducedMotion();

<div className="grid sm:grid-cols-2 gap-16 my-28">
  <div className="flex items-center justify-center">
    <motion.div className="dark:text-white text-5xl font-bold"
      initial={{ y: shouldReduceMotion ? 0 : 50, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      Title
    </motion.div>
  </div>
  <div className="flex justify-center">
    <motion.div className="dark:text-white text-5xl"
      initial={{ scale: shouldReduceMotion ? 1 : 1.5, opacity: 0 }}
      animate={{ scale: 1, opacity: 1 }}
      transition={{ duration: 0.75 }}
    >
      <div className="bg-red-500 h-64 w-64">
      </div>
    </motion.div>
  </div>
</div>`} />

          <div className="flex items-center gap-8 my-64">
            <motion.div className="bg-purple-500 h-32 w-32"
              style={{
                y: forwardsY,
                x: forwardsX
              }}
            />
            <motion.div className="bg-green-500 h-32 w-32"
              style={{
                y: backwardsY
              }}
            />
            <motion.div className="bg-purple-500 h-32 w-32"
              style={{
                y: forwardsY,
                x: backwardsX
              }}
            />
            <div className="bg-green-500 h-32 w-32"
            />
          </div>

          <Code code={`import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';

const { scrollYProgress } = useScroll()
const backwardsY = useTransform(scrollYProgress, [0, 1], ["0", "-700px"]);
const forwardsY = useTransform(scrollYProgress, [0, 1], ["0", "200px"]);
const backwardsX = useTransform(scrollYProgress, [0, 1], ["0", "-200px"]);
const forwardsX = useTransform(scrollYProgress, [0, 1], ["0", "200px"]);

<div className="flex items-center gap-8 my-64">
  <motion.div className="bg-purple-500 h-32 w-32"
    style={{
      y: forwardsY,
      x: forwardsX
    }}
  />
  <motion.div className="bg-green-500 h-32 w-32"
    style={{
      y: backwardsY
    }}
  />
  <motion.div className="bg-purple-500 h-32 w-32"
    style={{
      y: forwardsY,
      x: backwardsX
    }}
  />
  <div className="bg-green-500 h-32 w-32"
  />
</div>`} />

          <div className="flex justify-center my-24">
            <motion.div className="bg-blue-500 h-32 w-32"
              style={{
                scale
              }}
            />
          </div>

          <Code code={`import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
          
const { scrollYProgress } = useScroll()
const scale = useTransform(scrollYProgress, [0, 1], [1, 3]);

<div className="flex justify-center my-24">
  <motion.div className="bg-blue-500 h-32 w-32"
    style={{
      scale
    }}
  />
</div>`} />

          <div className="flex flex-col gap-10 space-y-10 my-16">
            <Square />
            <Square />
            <Square />
            <Square />
            <Square />
          </div>

          <Code code={`import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
          
function Square() {
  return (
    <>
      <motion.div
        initial={{ opacity: 0, scale: 0.75, y: 50 }}
        whileInView={{ opacity: 1, scale: 1, y: 0, transition: { duration: 0.75, type: "spring", stiffness: 300, damping: 20 } }}
        className="bg-yellow-500 h-52 w-52 rounded"
      ></motion.div>
    </>
  );
}

<div className="flex flex-col gap-20 space-y-20 my-16">
  <Square />
  <Square />
  <Square />
  <Square />
  <Square />
</div>`} />

        </div>
      </main >
    </>
  )
}