import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useSpring, animated } from 'react-spring'
import Code from '@components/Code';

export default function Spring() {
  const fadeIn = useSpring({ to: { opacity: 1 }, from: { opacity: 0 } })
  const rotate = useSpring({
    loop: true,
    from: { rotateZ: 0 },
    to: { rotateZ: 180 },
  })
  const slide = useSpring({
    loop: { reverse: true },
    from: { x: 0 },
    to: { x: 100 },
  })

  return (
    <>
      <Head>
        <title>React Spring | Next Animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 ">
          <h1 className="dark:text-white text-2xl font-semibold mb-2">React Spring</h1>
          <animated.div className="dark:text-white mt-4" style={fadeIn}>
            <h2 className="text-xl font-semibold mb-2">I will fade in</h2>
            <p>Sint ad aliqua irure nisi et nulla. Exercitation proident quis elit nisi velit non ipsum magna consequat pariatur cupidatat. Est occaecat dolor elit officia tempor ullamco non ea dolore consequat officia culpa dolor et.</p>
          </animated.div>

          <h2 className="text-xl font-semibold mt-8 dark:text-white mb-2">Rotate (Loop)</h2>
          <animated.div className="w-10 h-10 bg-red-500 rounded-md"
            style={{
              ...rotate,
            }}
          />
          
          <h2 className="text-xl font-semibold mt-8 dark:text-white mb-2">Slide (Loop)</h2>
          <animated.div className="w-10 h-10 bg-red-500 rounded-md"
            style={{
              ...slide,
            }}
          />

          <Code code={`import { useSpring, animated } from 'react-spring'

export default function Spring() {
  const fadeIn = useSpring({ to: { opacity: 1 }, from: { opacity: 0 } })
  const rotate = useSpring({
    loop: true,
    from: { rotateZ: 0 },
    to: { rotateZ: 180 },
  })
  const slide = useSpring({
    loop: { reverse: true },
    from: { x: 0 },
    to: { x: 100 },
  })
  
  return (
    <animated.div className="dark:text-white mt-4" style={fadeIn}>
      <h2 className="text-xl font-semibold mb-2">I will fade in</h2>
      <p>Sint ad aliqua irure nisi et nulla. Exercitation proident quis elit nisi velit non ipsum magna consequat pariatur cupidatat. Est occaecat dolor elit officia tempor ullamco non ea dolore consequat officia culpa dolor et.</p>
    </animated.div>

    <h2 className="text-xl font-semibold mt-8 dark:text-white mb-2">Rotate (Loop)</h2>
    <animated.div className="w-10 h-10 bg-red-500 rounded-md"
      style={{
        ...rotate,
      }}
    />
    
    <h2 className="text-xl font-semibold mt-8 dark:text-white mb-2">Slide (Loop)</h2>
    <animated.div className="w-10 h-10 bg-red-500 rounded-md"
      style={{
        ...slide,
      }}
    />
  )
}`} />

        </div>
      </main >
    </>
  )
}
